name: Security Audit

on:
  push:
    paths:
      - Cargo.lock
  schedule:
    - cron: '0 8 * * 1'  # ogni lunedì alle 08:00 UTC

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
